spring:
  application:
    name: "apigateway"
  config:
    import: "configserver:http://localhost:8071"
  cloud:
    gateway:
      globalcors:
#        cors-configurations:
#          '[/**]':
#            allowedOrigins: "http://localhost:5173"
#            allowedMethods:
#              - GET
#              - POST
#              - PUT
#              - DELETE
#        add-to-simple-url-handler-mapping: true
      discovery:
        locator:
          enabled: false
          lower-case-service-id: true
    config:
      name: common, jwt-common, apigateway
debug: true
logging:
  level:
    org:
      springframework:
        cloud: TRACE
#          gateway: TRACE